export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  CREATE_DELIVERY: "/create-delivery",
  WAY_MANAGEMENT: "/way-management",
  CUSTOMER_SERVICE: "/customer-service",
  CUSTOMER_PORTAL: "/customer",
  SUPERVISOR: "/supervisor",
  SUPERVISOR_PICKUP: "/supervisor-pickup",
  SUPERVISOR_WAYPLAN: "/supervisor-wayplan",
  DATA_ENTRY: "/data-entry",
  DELIVERYMEN: "/deliverymen",
  MERCHANTS: "/merchants",
  SETTINGS: "/settings",
  REPORTING: "/reporting",
} as const;
